version: '3'
services:

  postgres:
    image: 'postgres:alpine'
    volumes:
      - srm-postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=srm

volumes:
  srm-postgres-volume: