INSERT INTO REALM (NAME, CURRENCY_ID) VALUES ('Wefin', 1);
INSERT INTO REALM (NAME, CURRENCY_ID) VALUES ('Anoes', 2);

INSERT INTO CURRENCY_EXCHANGE_RATE (ORIGIN_CURRENCY_ID, TARGET_CURRENCY_ID, EXCHANGE_RATE) VALUES (1, 2, 2.5);
INSERT INTO CURRENCY_EXCHANGE_RATE (ORIGIN_CURRENCY_ID, TARGET_CURRENCY_ID, EXCHANGE_RATE) VALUES (2, 1, 0.4);

INSERT INTO PRODUCT_VALUE (PRODUCT_ID, CURRENCY_ID, PRODUCT_VALUE) VALUES (1, 1, 10);
INSERT INTO PRODUCT_VALUE (PRODUCT_ID, CURRENCY_ID, PRODUCT_VALUE) VALUES (1 , 2, 25);

INSERT INTO PRODUCT_VALUE (PRODUCT_ID, CURRENCY_ID, PRODUCT_VALUE) VALUES (2, 1, 10);
INSERT INTO PRODUCT_VALUE (PRODUCT_ID, CURRENCY_ID, PRODUCT_VALUE) VALUES (2, 2, 25);

INSERT INTO PRODUCT_VALUE (PRODUCT_ID, CURRENCY_ID, PRODUCT_VALUE) VALUES (3, 1, 10);
INSERT INTO PRODUCT_VALUE (PRODUCT_ID, CURRENCY_ID, PRODUCT_VALUE) VALUES (3, 2, 25);