INSERT INTO CURRENCY (NAME) VALUES ('Ouro Real');
INSERT INTO CURRENCY (NAME) VALUES ('Tibar');

INSERT INTO PRODUCT (NAME) VALUES ('Pele');
INSERT INTO PRODUCT (NAME) VALUES ('Hidromel');
INSERT INTO PRODUCT (NAME) VALUES ('Madeira');